// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPFmKSasEzoleypbB2pTCDZjXX7dfNw8',
    appId: '1:862889084980:web:88db731e4d42474081a261',
    messagingSenderId: '862889084980',
    projectId: 'studyswap-1bdf3',
    authDomain: 'studyswap-1bdf3.firebaseapp.com',
    storageBucket: 'studyswap-1bdf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8s0USuG2bKh8WaLs8I85uENzXEYapUA',
    appId: '1:862889084980:android:ddc46ed291adf83e81a261',
    messagingSenderId: '862889084980',
    projectId: 'studyswap-1bdf3',
    storageBucket: 'studyswap-1bdf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23d6S4Six-Y3R0XVq9XP6l7MK0roaJSI',
    appId: '1:862889084980:ios:6170fd89abd99eb281a261',
    messagingSenderId: '862889084980',
    projectId: 'studyswap-1bdf3',
    storageBucket: 'studyswap-1bdf3.firebasestorage.app',
    iosBundleId: 'com.example.studyswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23d6S4Six-Y3R0XVq9XP6l7MK0roaJSI',
    appId: '1:862889084980:ios:6170fd89abd99eb281a261',
    messagingSenderId: '862889084980',
    projectId: 'studyswap-1bdf3',
    storageBucket: 'studyswap-1bdf3.firebasestorage.app',
    iosBundleId: 'com.example.studyswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCPFmKSasEzoleypbB2pTCDZjXX7dfNw8',
    appId: '1:862889084980:web:ab247c9239e1a1e781a261',
    messagingSenderId: '862889084980',
    projectId: 'studyswap-1bdf3',
    authDomain: 'studyswap-1bdf3.firebaseapp.com',
    storageBucket: 'studyswap-1bdf3.firebasestorage.app',
  );
}
